version: "3.9"

services:
    p2p_messenger:
        image: p2p_messenger:${VERSION}
        build:
            context: .
            dockerfile: Dockerfile
        command: "python main.py"
        env_file: .env
        # stdin_open: true
        # tty: true